import { describe, it, expect } from "vitest";
import {
  buildIncidentReport,
  renderMarkdown,
  renderText,
  generateReport,
  type IncidentReport,
} from "../src/utils/reportGenerator.js";
import type { AnalysisResult } from "../src/utils/types.js";

function mockResult(overrides?: Partial<AnalysisResult>): AnalysisResult {
  return {
    events: [
      { timestamp: "2024-03-08T14:02:00Z", service: "payment-service", severity: "error", message: "connection refused", lineNumber: 1 },
      { timestamp: "2024-03-08T14:02:01Z", service: "redis", severity: "warning", message: "scaled to 0", lineNumber: 2 },
    ],
    signals: [
      { label: "Connection refused", description: "Repeated pattern", severity: "error", count: 2 },
    ],
    summary: {
      whatHappened: "Services experienced connection failures.",
      likelyRootCause: "Redis became unavailable.",
      confidence: 85,
      impactedServices: ["payment-service", "redis"],
      suggestedNextSteps: ["Verify Redis availability", "Check deployment events"],
    },
    rawLineCount: 2,
    ...overrides,
  };
}

describe("buildIncidentReport", () => {
  it("builds report from analysis result", () => {
    const result = mockResult();
    const report = buildIncidentReport(result);
    expect(report.incidentSummary).toBe(result.summary.whatHappened);
    expect(report.rootCause).toBe(result.summary.likelyRootCause);
    expect(report.impact).toEqual(result.summary.impactedServices);
    expect(report.timeline).toHaveLength(2);
    expect(report.investigationSteps).toHaveLength(2);
  });

  it("handles empty events", () => {
    const result = mockResult({ events: [], summary: { ...mockResult().summary, impactedServices: [] } });
    const report = buildIncidentReport(result);
    expect(report.timeline).toHaveLength(0);
    expect(report.impact).toContain("unknown-service");
  });
});

describe("renderMarkdown", () => {
  it("produces markdown with expected sections", () => {
    const report: IncidentReport = {
      incidentSummary: "Test summary",
      impact: ["svc1"],
      timeline: [{ time: "14:02:00", service: "svc1", message: "msg" }],
      rootCause: "Test root cause",
      contributingFactors: ["factor1"],
      mitigationRecovery: "No recovery observed.",
      investigationSteps: ["step1"],
    };
    const md = renderMarkdown(report, "My Report");
    expect(md).toContain("# My Report");
    expect(md).toContain("## 1. Incident Summary");
    expect(md).toContain("## 2. Impact");
    expect(md).toContain("## 3. Timeline");
    expect(md).toContain("## 4. Root Cause");
    expect(md).toContain("Test summary");
    expect(md).toContain("Generated by SOLID");
  });
});

describe("renderText", () => {
  it("produces plain text with expected headers", () => {
    const report: IncidentReport = {
      incidentSummary: "Test",
      impact: [],
      timeline: [],
      rootCause: "Cause",
      contributingFactors: [],
      mitigationRecovery: "None",
      investigationSteps: [],
    };
    const text = renderText(report);
    expect(text).toContain("INCIDENT SUMMARY");
    expect(text).toContain("ROOT CAUSE");
  });
});

describe("generateReport", () => {
  it("returns markdown string for markdown format", () => {
    const result = mockResult();
    const out = generateReport(result, "markdown");
    expect(typeof out).toBe("string");
    expect(out).toContain("# ");
  });

  it("returns JSON object for json format", () => {
    const result = mockResult();
    const out = generateReport(result, "json");
    expect(typeof out).toBe("object");
    expect(out).toHaveProperty("incidentSummary");
    expect(out).toHaveProperty("timeline");
  });

  it("returns text string for text format", () => {
    const result = mockResult();
    const out = generateReport(result, "text");
    expect(typeof out).toBe("string");
    expect(out).toContain("INCIDENT SUMMARY");
  });
});
