/**
 * solid report <file> — Generate a markdown or JSON incident report.
 */

import type { Command } from "commander";
import { writeFile } from "fs/promises";
import ora from "ora";
import { analyzeLogs } from "../services/analyzer.js";
import { readLogFile } from "../utils/files.js";
import { FileNotFoundError, EmptyFileError } from "../utils/files.js";
import { formatError, type ColorMode } from "../utils/formatter.js";
import { REPORT_DEFAULT_OUTPUT, REPORT_DEFAULT_TITLE } from "../utils/constants.js";
import { formatTimestampForDisplay } from "../utils/parser.js";
import type { AnalysisResult } from "../utils/types.js";

export function registerReport(program: Command, options: { noColor?: boolean }) {
  const colorMode: ColorMode = options.noColor ? "off" : "on";

  return program
    .command("report <file>")
    .description("Generate a markdown incident report")
    .option("--output <file>", "Output path", REPORT_DEFAULT_OUTPUT)
    .option("--title <title>", "Report title", REPORT_DEFAULT_TITLE)
    .option("--json", "Generate JSON report instead of markdown")
    .action(async (
      file: string,
      cmdOpts: { output?: string; title?: string; json?: boolean },
      actionCommand?: { parent?: { opts(): { color?: boolean } } }
    ) => {
      const noColor = options.noColor ?? actionCommand?.parent?.opts?.()?.color === false;
      const color: ColorMode = noColor ? "off" : "on";

      try {
        const rawLines = await readLogFile(file);
        const spinner = ora("Generating report...").start();
        const { result } = await analyzeLogs(rawLines);
        const outPath = cmdOpts.output ?? REPORT_DEFAULT_OUTPUT;
        const title = cmdOpts.title ?? REPORT_DEFAULT_TITLE;

        const content = cmdOpts.json
          ? JSON.stringify(reportJson(result), null, 2)
          : reportMarkdown(result, title);

        await writeFile(outPath, content, "utf-8");
        spinner.succeed(`Report generated: ${outPath}`);
      } catch (err) {
        if (err instanceof FileNotFoundError) {
          console.error(formatError(`Could not read file: ${err.path}`, colorMode));
        } else if (err instanceof EmptyFileError) {
          console.error(formatError(`File is empty: ${err.path}`, colorMode));
        } else {
          console.error(formatError(err instanceof Error ? err.message : String(err), colorMode));
        }
        process.exit(1);
      }
    });
}

function reportMarkdown(result: AnalysisResult, title: string): string {
  const lines: string[] = [];
  lines.push(`# ${title}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(result.summary.whatHappened);
  lines.push("");
  lines.push("## Timeline");
  lines.push("");
  for (const e of result.events) {
    const time = formatTimestampForDisplay(e.timestamp);
    lines.push(`- **${time}** \`${e.service}\` [${e.severity}] ${e.message}`);
  }
  lines.push("");
  lines.push("## Signals");
  lines.push("");
  for (const s of result.signals) {
    const desc = s.description ? ` — ${s.description}` : "";
    const count = s.count != null ? ` (${s.count}x)` : "";
    lines.push(`- **${s.label}**${desc}${count}`);
  }
  lines.push("");
  lines.push("## Likely Root Cause");
  lines.push("");
  lines.push(result.summary.likelyRootCause);
  lines.push("");
  lines.push(`**Confidence:** ${result.summary.confidence}%`);
  lines.push("");
  lines.push("## Impacted Services");
  lines.push("");
  for (const svc of result.summary.impactedServices) {
    lines.push(`- ${svc}`);
  }
  lines.push("");
  lines.push("## Suggested Next Steps");
  lines.push("");
  result.summary.suggestedNextSteps.forEach((step, i) => {
    lines.push(`${i + 1}. ${step}`);
  });
  lines.push("");
  lines.push("## Notes");
  lines.push("");
  lines.push("Generated by SOLID CLI prototype. No persistence enabled.");
  return lines.join("\n");
}

function reportJson(result: AnalysisResult): Record<string, unknown> {
  return {
    summary: result.summary,
    timeline: result.events.map((e) => ({
      timestamp: e.timestamp,
      service: e.service,
      severity: e.severity,
      message: e.message,
    })),
    signals: result.signals,
    rawLineCount: result.rawLineCount,
  };
}
