/**
 * Incident report generator for CLI.
 * Produces structured post-mortem from analysis. No re-parsing or LLM.
 */

import type { AnalysisResult } from "./types.js";
import { formatTimestampForDisplay } from "./parser.js";

export type ReportFormat = "markdown" | "json" | "text";

export interface IncidentReport {
  incidentSummary: string;
  impact: string[];
  timeline: Array<{ time: string; service: string; message: string }>;
  rootCause: string;
  contributingFactors: string[];
  mitigationRecovery: string;
  investigationSteps: string[];
}

const RECOVERY_PATTERNS = [
  /backup.*success|using backup|fallback|retry.*success/i,
  /marked up|healthy|recovered|restored/i,
  /200|201|completed successfully/i,
];

function deriveContributingFactors(result: AnalysisResult): string[] {
  const factors: string[] = [];
  const rootLower = result.summary.likelyRootCause.toLowerCase();
  for (const s of result.signals) {
    const label = s.label ?? "";
    const desc = s.description ?? "";
    const combined = (label + " " + desc).toLowerCase();
    if (combined.length < 3) continue;
    if (rootLower.includes(label.toLowerCase().slice(0, 20))) continue;
    factors.push(desc ? label + ": " + desc : label);
  }
  return [...new Set(factors)].slice(0, 6);
}

function deriveMitigationRecovery(result: AnalysisResult): string {
  const recoveryEvents = result.events.filter((e) =>
    RECOVERY_PATTERNS.some((p) => p.test(e.message))
  );
  if (recoveryEvents.length > 0) {
    return recoveryEvents
      .map((e) => formatTimestampForDisplay(e.timestamp) + " — " + e.service + ": " + e.message.slice(0, 120))
      .join(". ");
  }
  const last = result.events[result.events.length - 1];
  if (last) {
    return "Last observed event: " + last.service + " — " + last.message.slice(0, 150);
  }
  return "No explicit recovery observed in the timeline.";
}

export function buildIncidentReport(result: AnalysisResult): IncidentReport {
  const timeline = result.events.map((e) => ({
    time: formatTimestampForDisplay(e.timestamp),
    service: e.service,
    message: e.message,
  }));

  return {
    incidentSummary: result.summary.whatHappened || "No summary available.",
    impact: result.summary.impactedServices?.length ? result.summary.impactedServices : ["unknown-service"],
    timeline,
    rootCause: result.summary.likelyRootCause || "Insufficient evidence for a single root cause.",
    contributingFactors: deriveContributingFactors(result),
    mitigationRecovery: deriveMitigationRecovery(result),
    investigationSteps: result.summary.suggestedNextSteps ?? [],
  };
}

export function renderMarkdown(report: IncidentReport, title = "Incident Report"): string {
  const lines: string[] = [];
  lines.push("# " + title);
  lines.push("");
  lines.push("## 1. Incident Summary");
  lines.push("");
  lines.push(report.incidentSummary);
  lines.push("");
  lines.push("## 2. Impact");
  lines.push("");
  for (const svc of report.impact) lines.push("- " + svc);
  lines.push("");
  lines.push("## 3. Timeline");
  lines.push("");
  for (const e of report.timeline) {
    lines.push(e.time + " — " + e.service + ": " + e.message);
  }
  lines.push("");
  lines.push("## 4. Root Cause");
  lines.push("");
  lines.push(report.rootCause);
  lines.push("");
  lines.push("## 5. Contributing Factors");
  lines.push("");
  if (report.contributingFactors.length) {
    for (const f of report.contributingFactors) lines.push("- " + f);
  } else {
    lines.push("None identified beyond the primary root cause.");
  }
  lines.push("");
  lines.push("## 6. Mitigation / Recovery");
  lines.push("");
  lines.push(report.mitigationRecovery);
  lines.push("");
  lines.push("## 7. Investigation Steps");
  lines.push("");
  if (report.investigationSteps.length) {
    for (const step of report.investigationSteps) lines.push("- " + step);
  } else {
    lines.push("- Correlate with metrics and deployment events for the same time window.");
  }
  lines.push("");
  lines.push("---");
  lines.push("*Generated by SOLID.*");
  return lines.join("\n");
}

export function renderText(report: IncidentReport): string {
  const lines: string[] = [];
  lines.push("INCIDENT SUMMARY");
  lines.push("================");
  lines.push(report.incidentSummary);
  lines.push("");
  lines.push("IMPACT");
  lines.push("======");
  for (const svc of report.impact) lines.push("  - " + svc);
  lines.push("");
  lines.push("TIMELINE");
  lines.push("========");
  for (const e of report.timeline) {
    lines.push("  " + e.time + " — " + e.service + ": " + e.message);
  }
  lines.push("");
  lines.push("ROOT CAUSE");
  lines.push("==========");
  lines.push(report.rootCause);
  lines.push("");
  lines.push("CONTRIBUTING FACTORS");
  lines.push("====================");
  for (const f of report.contributingFactors) lines.push("  - " + f);
  if (!report.contributingFactors.length) lines.push("  None identified.");
  lines.push("");
  lines.push("MITIGATION / RECOVERY");
  lines.push("=====================");
  lines.push(report.mitigationRecovery);
  lines.push("");
  lines.push("INVESTIGATION STEPS");
  lines.push("===================");
  for (const step of report.investigationSteps) lines.push("  - " + step);
  if (!report.investigationSteps.length) lines.push("  - Correlate with metrics and deployment events.");
  return lines.join("\n");
}

export function generateReport(
  result: AnalysisResult,
  format: ReportFormat,
  title = "Incident Report"
): string | IncidentReport {
  const report = buildIncidentReport(result);
  if (format === "json") return report;
  if (format === "text") return renderText(report);
  return renderMarkdown(report, title);
}
